### PR TITLE
[Fix] Ingress class processing in fullsync

### PR DESCRIPTION
**Pull request by swathinsankaran**
This commit takes care of the ingress class processing during fullsync.

### CODE REVIEW

**Review by chauhanshubham — APPROVED** [review]

**Comment by swathinsankaran** [comment]
build ako

**Comment by swathinsankaran** [comment]
build ako

**Review by akshayhavile — APPROVED** [review]

**Comment by swathinsankaran** [comment]
build ako

**Comment by swathinsankaran** [comment]
build ako

**Pull request merged**
