### PR TITLE
AV-212517: Clean buffer/cache for smooth run of unit tests

### PR DESCRIPTION
**Pull request by ashishnayak96**
Added cleaning of buffer/cache at start and memory intensive tests. (also on few random tests 😄 )

### CODE REVIEW

**Comment by Dhivyaaj** [comment]
No JIRA Ids found for the PR. Jira id is mandatory to update fix version in jira.                                            Please update respective Jira id in PR title or commit message                                            if the PR is intented for default branches of repo.                                            For mandatory exemptions, comment trigger phrase 'skip jira-id-check' in PR.                                            For manual trigger, comment trigger phrase 'run jira-id-check' in PR.

**Comment by Dhivyaaj** [comment]
No JIRA Ids found for the PR. Jira id is mandatory to update fix version in jira.                                            Please update respective Jira id in PR title or commit message                                            if the PR is intented for default branches of repo.                                            For mandatory exemptions, comment trigger phrase 'skip jira-id-check' in PR.                                            For manual trigger, comment trigger phrase 'run jira-id-check' in PR.

**Comment by ashishnayak96** [comment]
build ako

**Review by pkoshtavmware — APPROVED** [review]
LGTM

**Comment by pkoshtavmware** [comment]
I believe it might also need to be changed at ako-operator/makefile.
@DixitAakash Could you please confirm ?

**Review by DixitAakash — DISMISSED** [review]

**Comment by DixitAakash** [comment]
> I believe it might also need to be changed at ako-operator/makefile. @DixitAakash Could you please confirm ?

Should not be required as we only have one suite (two test files) and they don't do any memory intensive operations.

**Comment by arihantg** [comment]
This will clear the buffer in our devboxes as well . should we add it as cronjob in the jenkins workers?

**Comment by ashishnayak96** [comment]
build ako

**Pull request closed without merging**
