### PR TITLE
A few miscellaneous fixes and updates to docs/tests/utility functions.

### PR DESCRIPTION
**Pull request by chauhanshubham**
Individual commit messages are self-explanatory.

### CODE REVIEW

**Comment by chauhanshubham** [comment]
build ako

**Review by monotosh-avi — DISMISSED** [review]

**Comment by chauhanshubham** [comment]
build ako

**Comment by chauhanshubham** [comment]
build ako

**Review by sudswasavi — COMMENTED** [review]
We could keep the doc PRs separate from code PRs from the next time.

**Review by sudswasavi — APPROVED** [review]

**Review by hemantavi — APPROVED** [review]

**Pull request merged**
