### PR TITLE
AV-221886: Enable both EPSlice and pod informer on NPL mode

### PR DESCRIPTION
**Pull request by ashishnayak96**
Context:
Was enabling either EPS or Pod informer in NPL mode. 
Fix:
Enable both EPS and Pod informer in NPL mode(required). EP will be enabled only when NPL and EPS is disabled.

### CODE REVIEW

**Comment by ashishnayak96** [comment]
build ako

**Comment by ashishnayak96** [comment]
build ako

**Comment by ashishnayak96** [comment]
build ako

**Comment by ashishnayak96** [comment]
build ako

**Comment by ashishnayak96** [comment]
build ako

**Review by DixitAakash — APPROVED** [review]
LGTM

**Review by akshayhavile — APPROVED** [review]

**Pull request merged**
