### PR TITLE
AV-140383 Fixing LoadBalancer Service creation with named ports

### PR DESCRIPTION
**Pull request by aaha97**

### CODE REVIEW

**Comment by anish-avi** [comment]
AKO PR Sanity Check failed

**Review by monotosh-avi — APPROVED** [review]

**Review by akshayhavile — APPROVED** [review]

**Comment by anish-avi** [comment]
AKO PR Sanity Check succeeded

**Comment by anish-avi** [comment]
AKO PR Sanity Check failed

**Comment by anish-avi** [comment]
AKO PR Sanity Check failed

**Comment by anish-avi** [comment]
AKO PR Sanity Check failed

**Pull request merged**
