### PR TITLE
AV-216533 : Add UT for uri validation for encoded segroup, network and cloud names

### PR DESCRIPTION
**Pull request by DixitAakash**

### CODE REVIEW

**Comment by DixitAakash** [comment]
build ako

**Comment by DixitAakash** [comment]
Test result :
`ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/namingtests	15.240s	coverage: 22.1% of statements in ./...`

**Review by akshayhavile — APPROVED** [review]

**Comment by akshayhavile** [comment]
build ako

**Comment by DixitAakash** [comment]
build ako

**Comment by DixitAakash** [comment]
Closing this PR as changes will be added to master branch.

**Pull request closed without merging**
