### PR TITLE
AV-179162: No Autogenerated domain for Dedicated Shard VS when AutoFQDN is flat or default

### PR DESCRIPTION
**Pull request by swathinsankaran**
This PR cherry-picks the #1175 PR.

### CODE REVIEW

**Comment by swathinsankaran** [comment]
build ako

**Comment by swathinsankaran** [comment]
build ako

**Comment by swathinsankaran** [comment]
build ako

**Review by DixitAakash — APPROVED** [review]
LGTM

**Review by arihantg — APPROVED** [review]

**Pull request merged**
