### PR TITLE
Addressing security vulnerabilities in net, text and sys packages

### PR DESCRIPTION
**Pull request by akshayhavile**
Ran security check locally 
-----
2022-10-20T09:47:21.124Z	INFO	Vulnerability scanning is enabled
2022-10-20T09:47:21.124Z	INFO	Secret scanning is enabled
2022-10-20T09:47:21.124Z	INFO	If your scanning is slow, please try '--security-checks vuln' to disable secret scanning
2022-10-20T09:47:21.124Z	INFO	Please see also https://aquasecurity.github.io/trivy/v0.32/docs/secret/scanning/#recommendation for faster secret detection
2022-10-20T09:47:21.132Z	INFO	Detected OS: photon
2022-10-20T09:47:21.132Z	INFO	Detecting Photon Linux vulnerabilities...
2022-10-20T09:47:21.133Z	INFO	Number of language-specific files: 1
2022-10-20T09:47:21.133Z	INFO	Detecting gobinary vulnerabilities...

ako:latest (photon 4.0)

Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
----------------------------
Running FT locally

### CODE REVIEW

**Review by swathinsankaran — APPROVED** [review]
LGTM

**Review by aaha97 — APPROVED** [review]
LGTM

**Comment by aaha97** [comment]
build ako

**Comment by akshayhavile** [comment]
@apalsule : local run is passing. 
ok github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/infratests	70.055s

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
@apalsule:  local run is passing.
ok github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/infratests 70.055s

**Comment by akshayhavile** [comment]
build ako

**Pull request merged**
