### PR TITLE
AV-212214: fix uri query encoding

### PR DESCRIPTION
**Pull request by akshayhavile**

### CODE REVIEW

**Comment by Dhivyaaj** [comment]
No JIRA Ids found for the PR. Jira id is mandatory to update fix version in jira.                                            Please update respective Jira id in PR title or commit message                                            if the PR is intented for default branches of repo.                                            For mandatory exemptions, comment trigger phrase 'skip jira-id-check' in PR.                                            For manual trigger, comment trigger phrase 'run jira-id-check' in PR.

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Review by ashishnayak96 — APPROVED** [review]
LGTM

**Review by arihantg — DISMISSED** [review]
LGTM

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
UT's are passed locally 
```
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/k8stest       30.410s coverage: 8.7% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/integrationtest       484.061s        coverage: 26.0% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/ingresstests  1012.948s       coverage: 38.6% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/evhtests      1686.325s       coverage: 37.9% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/evhtests      1591.711s       coverage: 37.3% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/dedicatedevhtests     692.467s        coverage: 27.9% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/dedicatedevhtests     788.464s        coverage: 28.3% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/oshiftroutetests      1312.991s       coverage: 32.7% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/bootuptests   20.130s coverage: 4.3% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/multicloudtests       170.462s        coverage: 8.2% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/advl4tests    46.707s coverage: 18.9% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/namespacesynctests    152.367s        coverage: 20.9% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/servicesapitests      78.950s coverage: 22.1% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/npltests      116.796s        coverage: 23.4% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/dedicatedvstests      187.453s        coverage: 30.0% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/hatests       33.825s coverage: 24.8% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/cnitests      103.530s        coverage: 13.0% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/cnitests      27.260s coverage: 12.7% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/infratests    0.951s
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/multitenancytests     70.593s coverage: 33.8% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/graphlayer    260.908s        coverage: 18.9% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/ingestion     270.615s        coverage: 3.0% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/status        314.784s        coverage: 16.0% of statements in ./...
```

**Review by arihantg — APPROVED** [review]

**Review by ashishnayak96 — APPROVED** [review]

**Comment by akshayhavile** [comment]
build ako

**Pull request merged**
