### PR TITLE
Cherry-picks from AKO 1.10.x branch to master

### PR DESCRIPTION
**Pull request by akshayhavile**
This PR contains cherry-picks from AKO 1.10.2 and 1.10.3 branch.

### CODE REVIEW

**Comment by akshayhavile** [comment]
build ako

**Review by swathinsankaran — COMMENTED** [review]
LGTM

**Review by swathinsankaran — APPROVED** [review]

**Comment by swathinsankaran** [comment]
build ako

**Review by aaha97 — DISMISSED** [review]
LGTM

**Comment by aaha97** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Review by swathinsankaran — APPROVED** [review]

**Pull request merged**
