### PR TITLE
AV-169804: Fix: Static routes are not getting deleted from controller when deleteConfig is set to true (#1058)

### PR DESCRIPTION
**Pull request by akshayhavile**
Porting changes to 1.9.2 from master

### CODE REVIEW

**Review by swathinsankaran — APPROVED** [review]

**Review by DixitAakash — APPROVED** [review]
LGTM

**Comment by akshayhavile** [comment]
build ako

**Review by aaha97 — APPROVED** [review]
LGTM

**Comment by aaha97** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Comment by swathinsankaran** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Comment by swathinsankaran** [comment]
build ako

**Pull request merged**
