### PR TITLE
AV-210248: Enable endpointslices for supporting graceful shutdown of …

### PR DESCRIPTION
**Pull request by ashishnayak96**
…pods

### CODE REVIEW

**Comment by akshayhavile** [comment]
Can one of the admins verify this patch?

**Comment by ashishnayak96** [comment]
buildako

**Comment by ashishnayak96** [comment]
build ako

**Comment by ashishnayak96** [comment]
build ako

**Comment by DixitAakash** [comment]
build ako

**Comment by ashishnayak96** [comment]
build ako

**Comment by pkoshtavmware** [comment]
build ako

**Comment by ashishnayak96** [comment]
build ako

**Comment by ashishnayak96** [comment]
build ako

**Comment by pkoshtavmware** [comment]
build ako

**Pull request closed without merging**
