### PR TITLE
Make status update get/list calls using informer cache

### PR DESCRIPTION
**Pull request by chauhanshubham**

### CODE REVIEW

**Comment by chauhanshubham** [comment]
build ako

**Comment by chauhanshubham** [comment]
build ako

**Comment by chauhanshubham** [comment]
build ako

**Comment by chauhanshubham** [comment]
build ako

**Comment by chauhanshubham** [comment]
build ako

**Review by sudswasavi — COMMENTED** [review]
@monotosh-avi / @chauhanshubham this change `may` introduce regression at this time of the release, shall we move it to a future version?

**Comment by chauhanshubham** [comment]
> @monotosh-avi / @chauhanshubham this change `may` introduce regression at this time of the release, shall we move it to a future version?

I'm fine with leaving this for the release post 1.6.1.

**Review by sudswasavi — APPROVED** [review]

**Review by monotosh-avi — APPROVED** [review]

**Pull request merged**
