### PR TITLE
Release-1.10.3: helm based installation changes

### PR DESCRIPTION
**Pull request by akshayhavile**

### CODE REVIEW

**Comment by Dhivyaaj** [comment]
No JIRA Ids found for the PR. Jira id is mandatory to update fix version in jira.                                            Please update respective Jira id in PR title or commit message                                            if the PR is intented for default branches of repo.                                            For mandatory exemptions, comment trigger phrase 'skip jira-id-check' in PR.                                            For manual trigger, comment trigger phrase 'run jira-id-check' in PR.

**Comment by akshayhavile** [comment]
skip jira-id-check

**Comment by akshayhavile** [comment]
build ako

**Review by swathinsankaran — APPROVED** [review]
LGTM.

@akshayhavile I have checked the steps to install AKO in a k8s cluster.
@DixitAakash could you please check the installation/upgrade steps in an Openshift cluster?

fixes #1241

**Pull request merged**
