### PR TITLE
AKO Operator changes

### PR DESCRIPTION
**Pull request by RiyaGaniga-avi**
AKO Operator changes for 1.3.3
Includes Updates in AKOO to include the new field of values.yaml - autoFQDN

### CODE REVIEW

**Comment by monotosh-avi** [comment]
build ako

**Review by sudswasavi — DISMISSED** [review]

**Review by hemantavi — CHANGES_REQUESTED** [review]
@RiyaGaniga-avi have you checked if the generated Statefulset has the env variable for `autoFqdn` in it? This variable should refer to the configmap's value. I think you need to add the key for `autoFqdn` here: https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/blob/master/ako-operator/controllers/utils.go#L69

**Comment by RiyaGaniga-avi** [comment]
build ako

**Review by hemantavi — DISMISSED** [review]

**Review by sudswasavi — APPROVED** [review]

**Comment by hemantavi** [comment]
@RiyaGaniga-avi can you please change the commit title to: `Add autoFQDN to AKO Operator's AKOConfig`

**Comment by hemantavi** [comment]
build ako

**Review by hemantavi — DISMISSED** [review]

**Comment by RiyaGaniga-avi** [comment]
build ako

**Comment by sudswasavi** [comment]
@RiyaGaniga-avi can you pls rebase your PR. @monotosh-avi 's fix needs to get included for the UTs to pass.

**Review by sudswasavi — APPROVED** [review]

**Review by hemantavi — APPROVED** [review]

**Pull request merged**
