### PR TITLE
AV-157761 Status update for IPv6 AKO

### PR DESCRIPTION
**Pull request by aaha97**
This PR adds code to update IPv6 IPs to status of ingress.
the priority for status ip is as follows 
public ip > ipv6 ip > ipv4 ip

### CODE REVIEW

**Comment by akshayhavile** [comment]
@aaha97 : Can you please describe what problem it tries to address?

**Review by akshayhavile — APPROVED** [review]

**Comment by aaha97** [comment]
> @aaha97 : Can you please describe what problem it tries to address?

updated the description for PR

**Comment by aaha97** [comment]
updating UTs results from local run
`ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/advl4tests	14.528s
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/bootuptests	1.688s
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/dedicatedvstests	79.886s
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/evhtests	278.205s
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/infratests	71.821s
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/ingresstests	474.420s
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/integrationtest	88.817s
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/k8stest	32.284s
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/multicloudtests	171.020s
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/multiclusteringresstests	77.950s
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/namespacesynctests	125.988s
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/npltests	76.406s
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/oshiftroutetests      793.807s
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/servicesapitests	22.206s`

**Comment by aaha97** [comment]
build ako

**Comment by swathinsankaran** [comment]
build ako

**Comment by swathinsankaran** [comment]
build ako

**Pull request merged**
