### PR TITLE
AV-168279: Add retry logic for kube-api access.

### PR DESCRIPTION
**Pull request by akshayhavile**

### CODE REVIEW

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Comment by swathinsankaran** [comment]
build ako

**Review by swathinsankaran — APPROVED** [review]
LGTM

**Comment by akshayhavile** [comment]
> @akshayhavile Should we consider porting other bug fixes also to this release?

@swathinsankaran: Which bug fixes are you talking about? I think we should limit the scope for these 2 issues only.

**Comment by akshayhavile** [comment]
build ako

**Review by DixitAakash — APPROVED** [review]

**Pull request merged**
