### PR TITLE
AV-216533 : Do not encode contents of the fields query param

### PR DESCRIPTION
**Pull request by DixitAakash**

### CODE REVIEW

**Review by akshayhavile — APPROVED** [review]

**Comment by DixitAakash** [comment]
build ako

**Review by arihantg — APPROVED** [review]

**Comment by DixitAakash** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Review by aaha97 — COMMENTED** [review]
LGTM

**Review by aaha97 — APPROVED** [review]

**Comment by akshayhavile** [comment]
Not required.

**Pull request closed without merging**
