### PR TITLE
[Gateway API] Fix panic when gateway deleted when handling secret

### PR DESCRIPTION
**Pull request by aaha97**

### CODE REVIEW

**Comment by Dhivyaaj** [comment]
No JIRA Ids found for the PR. Jira id is mandatory to update fix version in jira.                                            Please update respective Jira id in PR title or commit message                                            if the PR is intented for default branches of repo.                                            For mandatory exemptions, comment trigger phrase 'skip jira-id-check' in PR.                                            For manual trigger, comment trigger phrase 'run jira-id-check' in PR.

**Comment by aaha97** [comment]
skip jira-id-check

**Comment by aaha97** [comment]
build ako

**Comment by aaha97** [comment]
local run for gateway api graph layer UT changes
`go test .
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/graphlayer `

**Review by pkoshtavmware — APPROVED** [review]
LGTM

**Review by akshayhavile — APPROVED** [review]

**Pull request merged**
