### PR TITLE
Adding command to remove base image security vulnerabilities if any

### PR DESCRIPTION
**Pull request by RiyaGaniga-avi**

### CODE REVIEW

**Comment by RiyaGaniga-avi** [comment]
Redhat Image scan for AKO Operator is failing with the following error.

Screenshot 2022-03-22 at 10 45 56 PM

**Comment by RiyaGaniga-avi** [comment]
build ako

**Comment by RiyaGaniga-avi** [comment]
build ako

**Review by chauhanshubham — APPROVED** [review]

**Comment by chauhanshubham** [comment]
build ako

**Pull request merged**
