### PR TITLE
Fix: Failure in go build and go test in AKO

### PR DESCRIPTION
**Pull request by akshayhavile**
This is temporary fix till we resolve 
1. Upgrade all build vms to latest docker so that we will use golang:latest image for testing
2. Resolve buildvcs issue with permanent fix.

### CODE REVIEW

**Comment by Dhivyaaj** [comment]
No JIRA Ids found for the PR. Jira id is mandatory to update fix version in jira.                                            Please update respective Jira id in PR title or commit message                                            if the PR is intented for default branches of repo.                                            For mandatory exemptions, comment trigger phrase 'skip jira-id-check' in PR.                                            For manual trigger, comment trigger phrase 'run jira-id-check' in PR.

**Comment by akshayhavile** [comment]
skip jira-id-check

**Review by pkoshtavmware — APPROVED** [review]
LGTM

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Review by DixitAakash — APPROVED** [review]
LGTM

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Pull request merged**
