### PR TITLE
AV-210932 Improve UT runtime (evhtests, vippernstests)

### PR DESCRIPTION
**Pull request by aaha97**
this PR isolates changes required for https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pull/1339

file changes for evhtests and vippernstests

UT results

vippernstests
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/evhtests      1483.889s

evhtests
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/evhtests      1573.992s

### CODE REVIEW

**Comment by aaha97** [comment]
This PR requires fix addressed in https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pull/1513 before merging

**Review by DixitAakash — COMMENTED** [review]
@aaha97 Can we rebase this PR instead of adding the commit again from this PR https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pull/1513 now. Also, the changes look good to me but can you look at the lint issue that still exists.

**Review by DixitAakash — DISMISSED** [review]
@aaha97 Changes look good to me. But, can you please run the concerned UT's and paste the results for the latest changes.

**Comment by aaha97** [comment]
adding Updated results

ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/evhtests      1848.082s (vipperns)

ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/evhtests      2040.901s

**Review by DixitAakash — APPROVED** [review]
LGTM

**Comment by ashishnayak96** [comment]
build ako

**Review by ashishnayak96 — APPROVED** [review]
LGTM

**Pull request merged**
