### PR TITLE
AV-217295 : Delete the sslkeycert for router-default-cert secret on reboot if it has no reference

### PR DESCRIPTION
**Pull request by DixitAakash**

### CODE REVIEW

**Review by abhishekbsingh — APPROVED** [review]

**Comment by DixitAakash** [comment]
build ako

**Review by akshayhavile — APPROVED** [review]

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Comment by DixitAakash** [comment]
build ako

**Comment by DixitAakash** [comment]
Local UT run results :
```
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/k8stest	30.434s	coverage: 8.8% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/integrationtest	499.099s	coverage: 26.2% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/ingresstests	1101.073s	coverage: 39.0% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/evhtests	2039.421s	coverage: 38.0% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/evhtests	1846.799s	coverage: 37.8% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/dedicatedevhtests	692.532s	coverage: 28.3% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/dedicatedevhtests	788.522s	coverage: 28.6% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/oshiftroutetests	1313.089s	coverage: 33.0% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/bootuptests	20.134s	coverage: 4.0% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/multicloudtests	170.433s	coverage: 8.2% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/advl4tests	46.758s	coverage: 19.1% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/namespacesynctests	152.386s	coverage: 21.2% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/servicesapitests	79.011s	coverage: 22.3% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/npltests	116.804s	coverage: 23.7% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/dedicatedvstests	187.496s	coverage: 29.6% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/hatests	33.842s	coverage: 25.0% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/cnitests	103.544s	coverage: 13.1% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/cnitests	27.253s	coverage: 12.8% of statements in ./...

Charts:      1 passed, 1 total
Test Suites: 4 passed, 4 total
Tests:       9 passed, 9 total
Snapshot:    0 passed, 0 total

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/infratests	0.933s

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/urltests	15.260s	coverage: 21.6% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/graphlayer	290.919s	coverage: 18.0% of statements in ./...
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/ingestion	260.595s	coverage: 2.9% of statements in ./...
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/npltests	60.337s	coverage: 15.7% of statements in ./...
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/status	300.684s	coverage: 12.5% of statements in ./...
```

**Pull request merged**
