### PR TITLE
AV-205473 Update IP when node annotation is updated

### PR DESCRIPTION
**Pull request by aaha97**
This PR fixes the issue that was observed when calico updated the annotation with new IP but the internal IP was same and so AKO did not push the updated routes

### CODE REVIEW

**Comment by Dhivyaaj** [comment]
No JIRA Ids found for the PR. Jira id is mandatory to update fix version in jira.                                            Please update respective Jira id in PR title or commit message                                            if the PR is intented for default branches of repo.                                            For mandatory exemptions, comment trigger phrase 'skip jira-id-check' in PR.                                            For manual trigger, comment trigger phrase 'run jira-id-check' in PR.

**Comment by akshayhavile** [comment]
skip jira-id-check

**Review by akshayhavile — COMMENTED** [review]
Changes looks good. How can we test it?

**Comment by aaha97** [comment]
> Changes looks good. How can we test it?

I have added UT case to the changes now

**Review by akshayhavile — APPROVED** [review]
LGTM

**Comment by aaha97** [comment]
build ako

**Review by arihantg — APPROVED** [review]

**Comment by aaha97** [comment]
build ako

**Comment by aaha97** [comment]
build ako

**Comment by aaha97** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Pull request merged**
