### PR TITLE
AV-180638: Fix for the network profile for SCTP not coming as expected

### PR DESCRIPTION
**Pull request by swathinsankaran**
This PR fixes one regression introduced as part of the L4Rule and SSORule CRD code merge. The function `copier.Copy` that copies the value by using the field names was overwriting the application profile and network profile to an empty string. Because of this issue, the application profile and network profile were getting configured with their default values only every time.

TODO: FT

### CODE REVIEW

**Comment by swathinsankaran** [comment]
build ako

**Review by akshayhavile — COMMENTED** [review]
@swathinsankaran: Can we have UT/FT to cover this?

**Comment by akshayhavile** [comment]
build ako

**Comment by swathinsankaran** [comment]
UTs and fixes in UT is currently in-progress.

**Review by akshayhavile — APPROVED** [review]
@swathinsankaran: Overall changes looks good. Can error happen during copy? If yes, should we handle (atleast log that) so that in case of any wrong rest calls, we will get an idea.

**Review by akshayhavile — APPROVED** [review]
@swathinsankaran: Overall changes looks good. Can error happen during copy? If yes, should we handle (atleast log that) so that in case of any wrong rest calls, we will get an idea.

**Comment by swathinsankaran** [comment]
build ako

**Comment by swathinsankaran** [comment]
build ako

**Pull request merged**
