### PR TITLE
Start/Run informers after setting up event handlers

### PR DESCRIPTION
**Pull request by shubhamavi**
We should be running informers after the event handlers have been set-up. Prior to this the order was reverse.

### CODE REVIEW

**Comment by shubhamavi** [comment]
build ako

**Comment by shubhamavi** [comment]
build ako

**Comment by sudswasavi** [comment]
As discussed @monotosh-avi / @shubhamavi - it isn't entirely clear on what this PR is trying to solve. We are trading in a code path that is stable and may introduce regression, while I am not entirely denouncing this PR to be a good to have and not be the cause of any concern. Leave the decision to you folks.

**Comment by monotosh-avi** [comment]
> As discussed @monotosh-avi / @shubhamavi - it isn't entirely clear on what this PR is trying to solve. We are trading in a code path that is stable and may introduce regression, while I am not entirely denouncing this PR to be a good to have and not be the cause of any concern. Leave the decision to you folks.

I think this change is fine, and to me it looks like the current change makes the sequence of operations logical.

**Review by monotosh-avi — APPROVED** [review]

**Comment by shubhamavi** [comment]
> As discussed @monotosh-avi / @shubhamavi - it isn't entirely clear on what this PR is trying to solve. We are trading in a code path that is stable and may introduce regression. I am not entirely denouncing this PR and it may be a good to have and eventually may not be the cause of any concern. Leave the decision to you folks.

This is a pre-requisite to further configure informers (like adding cache.Indexers), which won't be possible if we run the informers first and then configure them. Configuring cache.Indexers for NsxAlbInfaSettings will be part of a subsequent PR, and this was intentionally kept separate due to the critical code under which it is present.

**Comment by anish-avi** [comment]
build ako

**Comment by anish-avi** [comment]
build ako

**Comment by anish-avi** [comment]
build ako

**Comment by anish-avi** [comment]
build ako

**Comment by anish-avi** [comment]
build ako

**Comment by anish-avi** [comment]
build ako

**Comment by anish-avi** [comment]
build ako

**Comment by anish-avi** [comment]
build ako

**Comment by anish-avi** [comment]
build ako

**Comment by shubhamavi** [comment]
build ako

**Review by sudswasavi — APPROVED** [review]

**Pull request merged**
