### PR TITLE
correct documentation for  aviinfrasetting

### PR DESCRIPTION
**Pull request by arihantg**

### CODE REVIEW

**Comment by Dhivyaaj** [comment]
No JIRA Ids found for the PR. Jira id is mandatory to update fix version in jira.                                            Please update respective Jira id in PR title or commit message                                            if the PR is intented for default branches of repo.                                            For mandatory exemptions, comment trigger phrase 'skip jira-id-check' in PR.                                            For manual trigger, comment trigger phrase 'run jira-id-check' in PR.

**Comment by arihantg** [comment]
skip jira-id-check

**Review by akshayhavile — APPROVED** [review]

**Comment by akshayhavile** [comment]
build ako

**Comment by arihantg** [comment]
build ako

**Review by swathinsankaran — APPROVED** [review]
LGTM

**Pull request merged**
