### PR TITLE
AV-221701 Removed tenant from cloud and segroup ref

### PR DESCRIPTION
**Pull request by abhishekbsingh**

### CODE REVIEW

**Comment by abhishekbsingh** [comment]
build ako

**Comment by abhishekbsingh** [comment]
build ako

**Review by akshayhavile — COMMENTED** [review]
@abhishekbsingh: Changes Looks good to me. Should we have one FT run in 30.2.x and 22.1.x to test changes about multi-tenancy?

**Comment by akshayhavile** [comment]
build ako

**Review by akshayhavile — APPROVED** [review]

**Comment by abhishekbsingh** [comment]
build ako

**Comment by abhishekbsingh** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Comment by abhishekbsingh** [comment]
build ako

**Pull request merged**
