### PR TITLE
Gateway FQDN fix and ClientPool cherry-picks from release-1.5.1 to master

### PR DESCRIPTION
**Pull request by chauhanshubham**

### CODE REVIEW

**Review by monotosh-avi — APPROVED** [review]

**Review by akshayhavile — APPROVED** [review]

**Comment by chauhanshubham** [comment]
fatal error: concurrent map writes

**Comment by chauhanshubham** [comment]
build ako

**Review by hemantavi — APPROVED** [review]

**Comment by chauhanshubham** [comment]
build ako

**Comment by chauhanshubham** [comment]
build ako

**Pull request merged**
