### PR TITLE
Fixed panic during AVI client creation

### PR DESCRIPTION
**Pull request by Rishabh-Baranwal**

### CODE REVIEW

**Comment by Rishabh-Baranwal** [comment]
build ako

**Comment by Rishabh-Baranwal** [comment]
build ako

**Comment by swathinsankaran** [comment]
@Rishabh-Baranwal Please raise a JIRA for this and mention it in the title or description. LGTM.

**Comment by akshayhavile** [comment]
@Rishabh-Baranwal Can you please paste FT run results for test_lbsvc.py, test_tls_ingress.py, test_tls_routes.py suites?

**Comment by Rishabh-Baranwal** [comment]
Closing - included in #968

**Pull request closed without merging**
