### PR TITLE
AV-218698 : String group type created with useRegex should be SG_TYPE_STRING

### PR DESCRIPTION
**Pull request by DixitAakash**

### CODE REVIEW

**Comment by DixitAakash** [comment]
build ako

**Comment by DixitAakash** [comment]
FT run results :

```
_STRING
```

**Comment by DixitAakash** [comment]
UT Local run :
```
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/k8stest	30.414s	coverage: 8.8% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/integrationtest	499.089s	coverage: 26.3% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/ingresstests	1101.068s	coverage: 39.1% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/evhtests	2039.360s	coverage: 38.1% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/evhtests	1846.752s	coverage: 37.6% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/dedicatedevhtests	692.523s	coverage: 28.3% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/dedicatedevhtests	788.525s	coverage: 28.7% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/oshiftroutetests	1313.107s	coverage: 33.0% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/bootuptests	20.150s	coverage: 4.1% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/multicloudtests	170.481s	coverage: 8.2% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/advl4tests	46.740s	coverage: 19.1% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/namespacesynctests	152.385s	coverage: 21.2% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/servicesapitests	79.045s	coverage: 22.3% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/npltests	116.792s	coverage: 23.8% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/dedicatedvstests	187.446s	coverage: 30.3% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/hatests	33.887s	coverage: 25.1% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/cnitests	103.559s	coverage: 13.1% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/cnitests	27.270s	coverage: 12.8% of statements in ./...

Charts:      1 passed, 1 total
Test Suites: 4 passed, 4 total
Tests:       9 passed, 9 total
Snapshot:    0 passed, 0 total

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/infratests

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/urltests


ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/graphlayer	290.930s	coverage: 18.0% of statements in ./...
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/ingestion	260.610s	coverage: 2.9% of statements in ./...
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/npltests	60.327s	coverage: 15.7% of statements in ./...
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/status	300.686s	coverage: 12.5% of statements in ./...
```

**Review by akshayhavile — APPROVED** [review]
LGTM

**Review by pkoshtavmware — APPROVED** [review]
LGTM

**Pull request merged**
