### PR TITLE
AV-194885 : Updated version to 1.12.1 in docs

### PR DESCRIPTION
**Pull request by jeyapradeen-avi**

### CODE REVIEW

**Comment by Dhivyaaj** [comment]
No JIRA Ids found for the PR. Jira id is mandatory to update fix version in jira.                                            Please update respective Jira id in PR title or commit message                                            if the PR is intented for default branches of repo.                                            For mandatory exemptions, comment trigger phrase 'skip jira-id-check' in PR.                                            For manual trigger, comment trigger phrase 'run jira-id-check' in PR.

**Comment by akshayhavile** [comment]
Can one of the admins verify this patch?

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Comment by DixitAakash** [comment]
@jeyapradeen-avi Can we change the version in line **108** in **docs/install/helm.md** to **1.11.1**, as we always set it to the last released version. Other changes look good.

**Comment by akshayhavile** [comment]
build ako

**Pull request merged**
