### PR TITLE
Updated supported k8s maxVersion to 1.26 in buildsettings

### PR DESCRIPTION
**Pull request by saurabhvaidvmware**

### CODE REVIEW

**Comment by saurabhvaidvmware** [comment]
build ako

**Review by akshayhavile — APPROVED** [review]

**Comment by akshayhavile** [comment]
build ako

**Comment by swathinsankaran** [comment]
build ako

**Review by swathinsankaran — APPROVED** [review]

**Comment by saurabhvaidvmware** [comment]
> @saurabhvaidvmware could you please take care of the ubuntu version in `.github/workflows/go.yml` with this PR?

I've updated it to 20.04

**Pull request merged**
