### PR TITLE
use first IP in case of multiple internal IPs for node (#1082)

### PR DESCRIPTION
**Pull request by akshayhavile**
cherry-pick from 1.9.2

### CODE REVIEW

**Comment by akshayhavile** [comment]
skip jira-id-check

**Comment by akshayhavile** [comment]
build ako

**Review by aaha97 — APPROVED** [review]
LGTM

**Comment by akshayhavile** [comment]
build ako

**Review by DixitAakash — APPROVED** [review]
LGTM

**Pull request merged**
