### PR TITLE
Adds a known issue to release-1.7.1 changelogs

### PR DESCRIPTION
**Pull request by swathinsankaran**
This PR adds a known issue to the changelogs of release 1.7.1.

### CODE REVIEW

**Review by aaha97 — APPROVED** [review]
Lgtm

**Review by akshayhavile — APPROVED** [review]

**Comment by swathinsankaran** [comment]
build ako

**Comment by swathinsankaran** [comment]
build ako

**Comment by swathinsankaran** [comment]
build ako

**Comment by swathinsankaran** [comment]
build ako

**Review by DixitAakash — APPROVED** [review]
LGTM

**Comment by swathinsankaran** [comment]
@akshayhavile Shall we merge this as the git checkout itself is failing and this is documentation PR?

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Comment by swathinsankaran** [comment]
build ako

**Review by apalsule — APPROVED** [review]

**Pull request merged**
