### PR TITLE
Do not delete vsvip cache for insecure passthrough VS deletion

### PR DESCRIPTION
**Pull request by monotosh-avi**
- vsvip objects should be deleted from cache only if controoler version
is >= 20.1.1 and the VS is not of type insecure passthrough. Else while
deleting the secure passthrough VS, vsvip won;t be pressent in the cache
and vsvip deletion would be skipped

### CODE REVIEW

**Comment by monotosh-avi** [comment]
build ako

**Comment by shubhamavi** [comment]
build ako

**Comment by monotosh-avi** [comment]
build ako

**Comment by monotosh-avi** [comment]
build ako

**Comment by monotosh-avi** [comment]
build ako

**Review by sudswasavi — APPROVED** [review]

**Review by shubhamavi — APPROVED** [review]

**Pull request merged**
