### PR TITLE
AV-195886: Fix for missing SSL port on adding HostRule with SSL cert to insecure Dedicated VS

### PR DESCRIPTION
**Pull request by saurabhvaidvmware**
UT Tests:

```
PASS
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/dedicatedvstests      154.323s
```
```
PASS
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/dedicatedevhtests     279.278s
```
```
PASS
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/evhtests      1042.875s
```
```
PASS
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/ingresstests  955.852s
```

### CODE REVIEW

**Comment by saurabhvaidvmware** [comment]
FT runs done with @pkoshtavmware 's branch AV-192477-eng-1 at commit 8f6ad380581508691e400e2417b1ba400ed22e98

```
+----------------------------------------------------------------------------------+----------------+---------------------+-------------+-------------+
| Absolute Path:Test case                                                          |     Results    |       Duration      |  Start Time |   End Time  |
+----------------------------------------------------------------------------------+----------------+---------------------+-------------+-------------+
|      Test Suite Path and Name : test/avitest/functional/ako/test_host_rules.py   |                |                     |             |             |
| ++++++++++++++++++++++++++++++++++++++++                                         |                |                     |             |             |
| Test_Host_Rules_SNI_Dedicated_Shard.test_create_config                           |     PASSED     |       00:01:43      |   05:47:59  |   05:49:43  |
| Test_Host_Rules_SNI_Dedicated_Shard.test_insecure_to_secure                      |     PASSED     |       00:00:36      |   05:49:43  |   05:50:20  |
| Test_Host_Rules_SNI_Dedicated_Shard.test_ecandrsacerts_ingress                   |     PASSED     |       00:00:19      |   05:50:20  |   05:50:40  |
| Test_Host_Rules_SNI_Dedicated_Shard.test_ecandrsacerts_ingressupdate             |     PASSED     |       00:00:23      |   05:50:40  |   05:51:03  |
| Test_Host_Rules_SNI_Dedicated_Shard.test_hostrule_secure_vs                      |     PASSED     |       00:00:37      |   05:51:03  |   05:51:41  |
| Test_Host_Rules_SNI_Dedicated_Shard.test_hostrule_allrefs_set_unset              |     PASSED     |       00:03:05      |   05:51:41  |   05:54:47  |
| Test_Host_Rules_SNI_Dedicated_Shard.test_hostrule_switch                         |     PASSED     |       00:00:51      |   05:54:47  |   05:55:38  |
| Test_Host_Rules_SNI_Dedicated_Shard.test_hostrule_analytics_policy               |     PASSED     |       00:00:32      |   05:55:38  |   05:56:11  |
| Test_Host_Rules_SNI_Dedicated_Shard.test_hostrule_fdqn_aliases                   |     PASSED     |       00:00:32      |   05:56:11  |   05:56:44  |
| Test_Host_Rules_SNI_Dedicated_Shard.test_hostrule_for_parent_vs_customports      |    SKIPPED     |       00:00:00      |   05:56:44  |   05:56:44  |
| Test_Host_Rules_SNI_Dedicated_Shard.test_hostrule_matchparam_update              |     PASSED     |       00:00:09      |   05:56:44  |   05:56:54  |
| Test_Host_Rules_SNI_Dedicated_Shard.test_hostrule_k8s_secret_create_delete       |     PASSED     |       00:00:24      |   05:56:54  |   05:57:18  |
| Test_Host_Rules_SNI_Dedicated_Shard.test_hostrule_k8s_secret_invalid_to_valid    |     PASSED     |       00:01:35      |   05:57:18  |   05:58:54  |
| Test_Host_Rules_SNI_Dedicated_Shard.test_hostrule_no_listeners                   |     FAILED     |       00:02:47      |   05:58:54  |   06:01:42  |
| Test_Host_Rules_SNI_Dedicated_Shard.test_delete_config_hostrule                  |     PASSED     |       00:00:50      |   06:01:43  |   06:02:33  |
| -------------------------------------------------------------------------------- |  ------------  |     -----------     | ----------- | ----------- |
|                                                                                  |   Passed: 13   |                     |             |             |
|                                                                                  |    Failed:1    |                     |             |             |
|  Total test cases: 15                                                            |    Skipped:1   | Total Time:00:14:32 |             |             |
+----------------------------------------------------------------------------------+----------------+---------------------+-------------+-------------+
```
```
+----------------------------------------------------------------------------------+----------------+---------------------+-------------+-------------+
| Absolute Path:Test case                                                          |     Results    |       Duration      |  Start Time |   End Time  |
+----------------------------------------------------------------------------------+----------------+---------------------+-------------+-------------+
|      Test Suite Path and Name : test/avitest/functional/ako/test_host_rules.py   |                |                     |             |             |
| ++++++++++++++++++++++++++++++++++++++++                                         |                |                     |             |             |
| Test_Host_Rules_EVH_Dedicated_Shard.test_create_config                           |     PASSED     |       00:00:45      |   06:04:43  |   06:05:28  |
| Test_Host_Rules_EVH_Dedicated_Shard.test_insecure_to_secure                      |     PASSED     |       00:00:22      |   06:05:28  |   06:05:50  |
| Test_Host_Rules_EVH_Dedicated_Shard.test_ecandrsacerts_ingress                   |     PASSED     |       00:00:19      |   06:05:50  |   06:06:10  |
| Test_Host_Rules_EVH_Dedicated_Shard.test_ecandrsacerts_ingressupdate             |     PASSED     |       00:00:24      |   06:06:10  |   06:06:34  |
| Test_Host_Rules_EVH_Dedicated_Shard.test_hostrule_secure_vs                      |     PASSED     |       00:00:37      |   06:06:34  |   06:07:12  |
| Test_Host_Rules_EVH_Dedicated_Shard.test_hostrule_allrefs_set_unset              |     PASSED     |       00:03:05      |   06:07:12  |   06:10:18  |
| Test_Host_Rules_EVH_Dedicated_Shard.test_hostrule_switch                         |     PASSED     |       00:00:51      |   06:10:18  |   06:11:09  |
| Test_Host_Rules_EVH_Dedicated_Shard.test_hostrule_analytics_policy               |     PASSED     |       00:00:32      |   06:11:09  |   06:11:42  |
| Test_Host_Rules_EVH_Dedicated_Shard.test_hostrule_fdqn_aliases                   |     PASSED     |       00:00:32      |   06:11:42  |   06:12:14  |
| Test_Host_Rules_EVH_Dedicated_Shard.test_hostrule_for_parent_vs_customports      |    SKIPPED     |       00:00:00      |   06:12:14  |   06:12:14  |
| Test_Host_Rules_EVH_Dedicated_Shard.test_hostrule_matchparam_update              |     PASSED     |       00:00:09      |   06:12:14  |   06:12:24  |
| Test_Host_Rules_EVH_Dedicated_Shard.test_hostrule_k8s_secret_create_delete       |     PASSED     |       00:00:23      |   06:12:24  |   06:12:47  |
| Test_Host_Rules_EVH_Dedicated_Shard.test_hostrule_k8s_secret_invalid_to_valid    |     PASSED     |       00:04:35      |   06:12:47  |   06:17:23  |
| Test_Host_Rules_EVH_Dedicated_Shard.test_hostrule_no_listeners                   |     PASSED     |       00:01:48      |   06:17:23  |   06:19:11  |
| Test_Host_Rules_EVH_Dedicated_Shard.test_delete_config_hostrule                  |     PASSED     |       00:00:50      |   06:19:11  |   06:20:02  |
| -------------------------------------------------------------------------------- |  ------------  |     -----------     | ----------- | ----------- |
|                                                                                  |   Passed: 14   |                     |             |             |
|                                                                                  |    Failed:0    |                     |             |             |
|  Total test cases: 15                                                            |    Skipped:1   | Total Time:00:15:19 |             |             |
+----------------------------------------------------------------------------------+----------------+---------------------+-------------+-------------+
```

**Comment by saurabhvaidvmware** [comment]
build ako

**Review by DixitAakash — APPROVED** [review]
LGTM

**Review by arihantg — APPROVED** [review]

**Review by pkoshtavmware — APPROVED** [review]
LGTM

**Comment by saurabhvaidvmware** [comment]
build ako

**Comment by saurabhvaidvmware** [comment]
```
PASS
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/k8stest       30.347s
```
```
PASS
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/bootuptests   20.085s
```

**Comment by saurabhvaidvmware** [comment]
build ako

**Comment by saurabhvaidvmware** [comment]
build ako

**Comment by saurabhvaidvmware** [comment]
```
PASS
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/multiclusteringresstests      94.189s
```

**Comment by saurabhvaidvmware** [comment]
build ako

**Review by akshayhavile — APPROVED** [review]

**Comment by saurabhvaidvmware** [comment]
build ako

**Comment by saurabhvaidvmware** [comment]
build ako

**Pull request merged**
