### PR TITLE
K8s supported version upgrade to 1.26 and TestUpdateIngressClassWithoutInfraSetting UT update

### PR DESCRIPTION
**Pull request by saurabhvaidvmware**
This commit adds a fix for UT TestUpdateIngressClassWithoutInfraSetting failing

cc @arihantg

### CODE REVIEW

**Review by arihantg — APPROVED** [review]

**Comment by akshayhavile** [comment]
build ako

**Comment by saurabhvaidvmware** [comment]
image
The suite failing in Sanity Check is passing for me.

**Comment by akshayhavile** [comment]
build ako

**Review by akshayhavile — APPROVED** [review]

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Pull request merged**
