### PR TITLE
AV-183230: Bugfix for extDNS incompatibility with shared-vip annotation

### PR DESCRIPTION
**Pull request by saurabhvaidvmware**

### CODE REVIEW

**Comment by saurabhvaidvmware** [comment]
build ako

**Comment by swathinsankaran** [comment]
@saurabhvaidvmware could you please add the UTs for this?

**Comment by saurabhvaidvmware** [comment]
> @saurabhvaidvmware Changes look good to me.. could you please add the UTs for this?

Hi @swathinsankaran , I have added 2 UTs for extDNS, 1 for default normal case and 1 for scenario related to this issue (with shared-vip)

**Review by swathinsankaran — APPROVED** [review]
LGTM

**Comment by saurabhvaidvmware** [comment]
build ako

**Comment by saurabhvaidvmware** [comment]
build ako

**Review by DixitAakash — APPROVED** [review]
LGTM

**Pull request merged**
