### PR TITLE
 AV-174358  get ingress/route status from api server instead of informer

### PR DESCRIPTION
**Pull request by arihantg**

### CODE REVIEW

**Comment by swathinsankaran** [comment]
@arihantg Changes look good to me. I was wondering why the number of commits is showing some  extra commits.

**Comment by arihantg** [comment]
> @arihantg Changes look good to me. I was wondering why the number of commits is showing some extra commits.

These are probably due to merging done during sync done with master

**Review by akshayhavile — APPROVED** [review]
@arihantg: Changes looks good. Did we run UT pipeline multiple time to check that we are not hitting same issue again?

**Review by swathinsankaran — APPROVED** [review]
LGTM

**Comment by arihantg** [comment]
> @arihantg: Changes looks good. Did we run UT pipeline multiple time to check that we are not hitting same issue again?
Have executed it multiple times on local and twice on jenkins.

**Pull request merged**
