### PR TITLE
AV-156959 Nodenetwork list mandatory fix for nsx-t vlan

### PR DESCRIPTION
**Pull request by aaha97**
nodenetworklist check mandatory for nsx-t vlan and vcenter cloud
update pool placement network for nsx-t vlan and vcenter cloud only

update vip placement network for nsx-t vlan

### CODE REVIEW

**Review by apalsule — APPROVED** [review]

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
@aaha97 can you please run tests all tests locally and paste result. OshiftRoute test suite has failed twice at same place.

**Comment by aaha97** [comment]
@akshayhavile oshiftroutestest is running successfully locally 

`PASS`
`ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/oshiftroutetests      792.625s`

**Comment by akshayhavile** [comment]
build ako

**Comment by swathinsankaran** [comment]
build ako

**Review by swathinsankaran — APPROVED** [review]
LGTM

**Comment by swathinsankaran** [comment]
build ako

**Comment by swathinsankaran** [comment]
build ako

**Comment by swathinsankaran** [comment]
build ako

**Comment by swathinsankaran** [comment]
build ako

**Comment by swathinsankaran** [comment]
@aaha97, Could you please check why the UTs are failing consistently for this PR?

**Review by apalsule — APPROVED** [review]

**Comment by apalsule** [comment]
run AKO-PR-Build-Sanity

**Comment by apalsule** [comment]
build ako

**Pull request merged**
