### PR TITLE
Updated systemconfiguration and controller permission to read access

### PR DESCRIPTION
**Pull request by saurabhvaidvmware**

### CODE REVIEW

**Comment by akshayhavile** [comment]
build ako

**Review by akshayhavile — COMMENTED** [review]
@saurabhvaidvmware: Can you please confirm with this settings we are not seeing any `warn` in AKO logs for any api access? Can you please attach AKO log for the same?

**Comment by saurabhvaidvmware** [comment]
[AKO log.txt](https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/files/10491198/AKO.log.txt)

**Review by akshayhavile — APPROVED** [review]

**Comment by swathinsankaran** [comment]
build ako

**Review by swathinsankaran — APPROVED** [review]
LGTM

**Comment by akshayhavile** [comment]
As it is doc PR, merging it without waiting for Sanity to pass.

**Pull request merged**
