### PR TITLE
[AV-154444] corrects the 'invalid type for address' warning logs coming in AKO log

### PR DESCRIPTION
**Pull request by swathinsankaran**
This PR corrects the 'invalid type for address' warning logs coming in AKO log.
fixes AV-154444

### CODE REVIEW

**Comment by swathinsankaran** [comment]
build ako

**Comment by swathinsankaran** [comment]
build ako

**Comment by swathinsankaran** [comment]
build ako

**Review by apalsule — APPROVED** [review]

**Review by akshayhavile — APPROVED** [review]

**Review by aaha97 — APPROVED** [review]
LGTM

**Pull request merged**
