### PR TITLE
AV-196893: Accessing L4 CRD in another namespace

### PR DESCRIPTION
**Pull request by akshayhavile**

### CODE REVIEW

**Comment by akshayhavile** [comment]
build ako

**Comment by aaha97** [comment]
@akshayhavile We should add a UT case for this

**Review by DixitAakash — DISMISSED** [review]
Changes look good. Like Arif pointed out, we should add UT's.

**Comment by akshayhavile** [comment]
build ako

**Review by DixitAakash — APPROVED** [review]
LGTM

**Review by aaha97 — APPROVED** [review]
LGTM

**Pull request merged**
