### PR TITLE
AV-219160 : HTTP/2 support for AKO - Backend

### PR DESCRIPTION
**Pull request by DixitAakash**
TO DO : Add UT's.

### CODE REVIEW

**Comment by DixitAakash** [comment]
build ako

**Comment by DixitAakash** [comment]
build ako

**Comment by DixitAakash** [comment]
build ako

**Comment by DixitAakash** [comment]
build ako

**Review by akshayhavile — APPROVED** [review]
@DixitAakash Overall changes LGTM. Have we run go mod tidy?

**Comment by DixitAakash** [comment]
> @DixitAakash Overall changes LGTM. Have we run go mod tidy?

@akshayhavile I had not, but I have run and updated the PR now. Will also run the UT's locally and and paste the results here.

**Comment by DixitAakash** [comment]
Local UT run results :
```
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/k8stest	30.401s	coverage: 8.8% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/integrationtest	499.077s	coverage: 26.3% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/ingresstests	1119.023s	coverage: 39.0% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/evhtests	2057.422s	coverage: 38.3% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/evhtests	1864.734s	coverage: 37.8% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/dedicatedevhtests	902.488s	coverage: 29.3% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/dedicatedevhtests	806.500s	coverage: 29.6% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/oshiftroutetests	1313.065s	coverage: 33.0% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/bootuptests	20.153s	coverage: 4.0% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/multicloudtests	170.480s	coverage: 8.2% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/advl4tests	46.711s	coverage: 19.1% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/namespacesynctests	152.384s	coverage: 21.2% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/servicesapitests	78.985s	coverage: 22.3% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/npltests	116.815s	coverage: 23.7% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/dedicatedvstests	397.442s	coverage: 31.2% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/hatests	33.831s	coverage: 25.0% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/cnitests	103.531s	coverage: 13.1% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/cnitests	27.601s	coverage: 12.8% of statements in ./...

Charts:      1 passed, 1 total
Test Suites: 4 passed, 4 total
Tests:       9 passed, 9 total
Snapshot:    0 passed, 0 total
Time:        72.774885ms

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/infratests	0.965s

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/urltests	15.250s	coverage: 21.6% of statements in ./...

ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/graphlayer	291.022s	coverage: 18.0% of statements in ./...
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/ingestion	260.863s	coverage: 2.9% of statements in ./...
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/npltests	60.327s	coverage: 15.7% of statements in ./...
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/status	300.730s	coverage: 12.5% of statements in ./...
```

**Review by akshayhavile — APPROVED** [review]

**Review by arihantg — APPROVED** [review]

**Comment by DixitAakash** [comment]
build ako

**Pull request merged**
