### PR TITLE
[bug-fix] Hostrule CRD fix

### PR DESCRIPTION
**Pull request by swathinsankaran**
This commit resolves an error occurred while configuring `HostRuleSecret` without the optional field `alternateCertificate` using client-go.

### CODE REVIEW

**Comment by chauhanshubham** [comment]
could you please also run `./hack/update-codegen-service-apis.sh` and verify if there are any updates to the auto-generated files?

**Comment by swathinsankaran** [comment]
@chauhanshubham I have executed both scripts and pushed the changes.

**Comment by chauhanshubham** [comment]
I think we might need additional nil checks now when AlternateCertificate is not provided?

**Review by akshayhavile — APPROVED** [review]

**Comment by swathinsankaran** [comment]
build ako

**Comment by swathinsankaran** [comment]
build ako

**Comment by chauhanshubham** [comment]
@aaha97 can you please review this?

**Comment by swathinsankaran** [comment]
build ako

**Comment by swathinsankaran** [comment]
build ako

**Comment by swathinsankaran** [comment]
build ako

**Comment by swathinsankaran** [comment]
closing this PR since the required field for the `alternateCertificate` is removed.

**Pull request closed without merging**
