### PR TITLE
Doc changes for release-1.7.4 

### PR DESCRIPTION
**Pull request by swathinsankaran**
This PR changes the version to 1.7.4 in all documents.

### CODE REVIEW

**Comment by Dhivyaaj** [comment]
No JIRA Ids found for the PR. Jira id is mandatory to update fix version in jira.                                            Please update respective Jira id in PR title or commit message                                            if the PR is intented for default branches of repo.                                            For mandatory exemptions, comment trigger phrase 'skip jira-id-check' in PR.                                            For manual trigger, comment trigger phrase 'run jira-id-check' in PR.

**Comment by swathinsankaran** [comment]
skip jira-id-check

**Comment by swathinsankaran** [comment]
build ako

**Comment by Dhivyaaj** [comment]
No JIRA Ids found for the PR. Jira id is mandatory to update fix version in jira.                                            Please update respective Jira id in PR title or commit message                                            if the PR is intented for default branches of repo.                                            For mandatory exemptions, comment trigger phrase 'skip jira-id-check' in PR.                                            For manual trigger, comment trigger phrase 'run jira-id-check' in PR.

**Comment by swathinsankaran** [comment]
skip jira-id-check

**Review by akshayhavile — APPROVED** [review]

**Review by DixitAakash — APPROVED** [review]

**Pull request merged**
