### PR TITLE
AV-198256: Fix pool placement network related issue. Support for K8 1.29

### PR DESCRIPTION
**Pull request by akshayhavile**
This PR includes:
1. K8 1.29 support
2. Regression fix for pool placement network.

### CODE REVIEW

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Review by arihantg — APPROVED** [review]
LGTM

**Review by pkoshtavmware — APPROVED** [review]
LGTM

**Review by DixitAakash — APPROVED** [review]
LGTM

**Pull request merged**
