### PR TITLE
AV-214519: AKO GW pod crashed with panic : interface {} is nil, not [……]objects.GatewayListenerStore

### PR DESCRIPTION
**Pull request by akshayhavile**
TODO:  UT

### CODE REVIEW

**Comment by akshayhavile** [comment]
build ako

**Review by pkoshtavmware — DISMISSED** [review]
LGTM

**Review by DixitAakash — DISMISSED** [review]
LGTM

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
```ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/k8stest       30.428s coverage: 8.8% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/integrationtest       499.040s        coverage: 26.1% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/ingresstests  1012.972s       coverage: 38.7% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/evhtests      1686.299s       coverage: 38.1% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/evhtests      1591.741s       coverage: 37.4% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/dedicatedevhtests     692.530s        coverage: 28.1% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/dedicatedevhtests     788.511s        coverage: 28.5% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/oshiftroutetests      1313.006s       coverage: 32.8% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/bootuptests   20.199s coverage: 4.0% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/multicloudtests       170.451s        coverage: 8.2% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/advl4tests    46.774s coverage: 19.0% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/namespacesynctests    152.429s        coverage: 21.1% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/servicesapitests      79.043s coverage: 22.2% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/npltests      116.788s        coverage: 23.5% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/dedicatedvstests      187.439s        coverage: 30.1% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/hatests       33.886s coverage: 24.9% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/cnitests      103.560s        coverage: 13.0% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/cnitests      27.263s coverage: 12.7% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/infratests    0.935s
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/multitenancytests     70.577s coverage: 34.0% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/graphlayer    288.953s        coverage: 19.0% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/ingestion     270.645s        coverage: 3.0% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/npltests      60.356s coverage: 16.5% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/status        314.762s        coverage: 16.1% of statements in ./...```

**Pull request merged**
