### PR TITLE
AV-159603 secure ingress with Istio fix

### PR DESCRIPTION
**Pull request by aaha97**

### CODE REVIEW

**Comment by akshayhavile** [comment]
@aaha97 We need to run FT suites against it.

**Review by akshayhavile — APPROVED** [review]
LGTM

**Review by apalsule — APPROVED** [review]

**Comment by swathinsankaran** [comment]
build ako

**Review by swathinsankaran — APPROVED** [review]
LGTM

**Comment by swathinsankaran** [comment]
build ako

**Comment by swathinsankaran** [comment]
@aaha97 we have to rebase this image. UTs are failing.

**Comment by akshayhavile** [comment]
build ako

**Comment by aaha97** [comment]
cherry-picked to master as part of another PR #1003

**Pull request closed without merging**
