### PR TITLE
AV-121758: AKO Pod restarted due to panic due to indexing issue. Copy object instead of sending reference

### PR DESCRIPTION
**Pull request by akshayhavile**
…

### CODE REVIEW

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Review by pkoshtavmware — APPROVED** [review]
LGTM

**Comment by akshayhavile** [comment]
build ako

**Review by arihantg — APPROVED** [review]

**Comment by akshayhavile** [comment]
build ako

**Pull request merged**
