### PR TITLE
[fix] AKO not honoring httprule updates in Openshift

### PR DESCRIPTION
**Pull request by swathinsankaran**
This PR fixes an issue where the AKO was not retrieving the routes correctly
for an empty path in the route configuration.

### CODE REVIEW

**Comment by swathinsankaran** [comment]
build ako

**Comment by swathinsankaran** [comment]
build ako

**Comment by swathinsankaran** [comment]
build ako

**Review by chauhanshubham — APPROVED** [review]
LGTM, Thanks!

**Review by akshayhavile — APPROVED** [review]

**Pull request merged**
