### PR TITLE
AV-220793: Fix: Restricting FQDN functionality is not working as per expectation in openshift route update scenario

### PR DESCRIPTION
**Pull request by akshayhavile**
…

### CODE REVIEW

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Review by ashishnayak96 — APPROVED** [review]
LGTM

**Comment by akshayhavile** [comment]
build ako

**Review by DixitAakash — APPROVED** [review]
LGTM

**Pull request merged**
