### PR TITLE
AV-207450 : L4Rule with SSL enabled not applied to L4 VS if license type is Enterprise with Cloud Services

### PR DESCRIPTION
**Pull request by DixitAakash**
This PR is cherry-pick for https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pull/1437

### CODE REVIEW

**Comment by DixitAakash** [comment]
build ako

**Comment by DixitAakash** [comment]
build ako

**Comment by DixitAakash** [comment]
build ako

**Comment by DixitAakash** [comment]
build ako

**Review by akshayhavile — APPROVED** [review]

**Review by arihantg — APPROVED** [review]

**Comment by DixitAakash** [comment]
build ako

**Pull request merged**
