### PR TITLE
Fix v6 IPAdress not updated

### PR DESCRIPTION
**Pull request by aaha97**

### CODE REVIEW

**Comment by Dhivyaaj** [comment]
No JIRA Ids found for the PR. Jira id is mandatory to update fix version in jira.                                            Please update respective Jira id in PR title or commit message                                            if the PR is intented for default branches of repo.                                            For mandatory exemptions, comment trigger phrase 'skip jira-id-check' in PR.                                            For manual trigger, comment trigger phrase 'run jira-id-check' in PR.

**Comment by akshayhavile** [comment]
skip jira-id-check

**Review by akshayhavile — COMMENTED** [review]
@aaha97: Overall changes looks good.
But Approach can be optimised by checking `IPtype` at VSVIP Rest layer before storing it to required fields (as currently we can't have IPV4 and IPV6 ip address as part `spec` definition of L4 object). This way we will
1. Avoid adding `if else` condition on each nodes/ files.
2. Adding it to cksum calculation.
3. Easier to do changes in future if required.

**Comment by akshayhavile** [comment]
skip jira-id-check

**Review by akshayhavile — APPROVED** [review]

**Comment by akshayhavile** [comment]
build ako

**Comment by Dhivyaaj** [comment]
No JIRA Ids found for the PR. Jira id is mandatory to update fix version in jira.                                            Please update respective Jira id in PR title or commit message                                            if the PR is intented for default branches of repo.                                            For mandatory exemptions, comment trigger phrase 'skip jira-id-check' in PR.                                            For manual trigger, comment trigger phrase 'run jira-id-check' in PR.

**Review by DixitAakash — APPROVED** [review]
Looks good in the current form.

**Comment by akshayhavile** [comment]
skip jira-id-check

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
Already merged as part of different PR. So closing.

**Pull request closed without merging**
