### PR TITLE
AV-177495: L4Rule bug fixes

### PR DESCRIPTION
**Pull request by swathinsankaran**
This PR contains the following changes:

  1. Introduces a new field "lbAlgorithmConsistentHashHdr" to configure the custom header when the "lbAlgorithmHash" is set as LB_ALGORITHM_CONSISTENT_HASH_CUSTOM_HEADER.

  2. Adds validation for the fields "lbAlgorithm", "lbAlgorithmHash" and "lbAlgorithmConsistentHashHdr".

  3. Adds two UTs to test invalid to valid transition of L4Rule CRD and to test validation introduced for "lbAlgorithm", "lbAlgorithmHash" and "lbAlgorithmConsistentHashHdr".

### CODE REVIEW

**Comment by swathinsankaran** [comment]
build ako

**Comment by swathinsankaran** [comment]
build ako

**Comment by swathinsankaran** [comment]
build ako

**Comment by Dhivyaaj** [comment]
run jira-id-check

**Comment by Dhivyaaj** [comment]
run jira-id-check

**Review by arihantg — APPROVED** [review]

**Review by DixitAakash — APPROVED** [review]
LGTM

**Pull request merged**
