### PR TITLE
Fix: Use mgmt network from confimap SE group if aviinfrasetting SEG is not present

### PR DESCRIPTION
**Pull request by akshayhavile**
…

### CODE REVIEW

**Comment by akshayhavile** [comment]
skip jira-idc-check

**Comment by akshayhavile** [comment]
skip jira-id-check

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
buil ako

**Comment by akshayhavile** [comment]
build ako

**Review by parimanur — APPROVED** [review]

**Pull request merged**
