### PR TITLE
AV-170763: Fixing security issues in go packages (#1062)

### PR DESCRIPTION
**Pull request by akshayhavile**
Security fixes.

### CODE REVIEW

**Comment by akshayhavile** [comment]
build ako

**Review by swathinsankaran — APPROVED** [review]
LGTM.

Could you please attach the results?

**Review by apalsule — APPROVED** [review]

**Review by aaha97 — APPROVED** [review]
LGTM

**Review by DixitAakash — APPROVED** [review]

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
@swathinsankaran 
2023-03-03T07:10:43.103Z	INFO	Need to update DB
2023-03-03T07:10:43.103Z	INFO	DB Repository: ghcr.io/aquasecurity/trivy-db
2023-03-03T07:10:43.103Z	INFO	Downloading DB...
35.84 MiB / 35.84 MiB [---------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 16.64 MiB p/s 2.4s
2023-03-03T07:10:46.899Z	INFO	Vulnerability scanning is enabled
2023-03-03T07:10:46.899Z	INFO	Secret scanning is enabled
2023-03-03T07:10:46.899Z	INFO	If your scanning is slow, please try '--security-checks vuln' to disable secret scanning
2023-03-03T07:10:46.900Z	INFO	Please see also https://aquasecurity.github.io/trivy/v0.32/docs/secret/scanning/#recommendation for faster secret detection
2023-03-03T07:10:49.201Z	INFO	Detected OS: photon
2023-03-03T07:10:49.201Z	INFO	Detecting Photon Linux vulnerabilities...
2023-03-03T07:10:49.202Z	INFO	Number of language-specific files: 1
2023-03-03T07:10:49.202Z	INFO	Detecting gobinary vulnerabilities...

ako:latest (photon 4.0)

Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

**Comment by akshayhavile** [comment]
build ako

**Pull request merged**
