### PR TITLE
AV-216533 : Do not encode contents of the fields query param

### PR DESCRIPTION
**Pull request by DixitAakash**

### CODE REVIEW

**Comment by DixitAakash** [comment]
build ako

**Review by akshayhavile — APPROVED** [review]
LGTM.

**Review by arihantg — APPROVED** [review]
LGTM

**Comment by DixitAakash** [comment]
build ako

**Comment by DixitAakash** [comment]
build ako

**Comment by DixitAakash** [comment]
UT run results on local dev box.

```
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/k8stest	30.392s	coverage: 9.0% of statements in ./...


ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/integrationtest	484.077s	coverage: 27.0% of statements in ./...


ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/ingresstests	975.912s	coverage: 39.4% of statements in ./...


sudo docker run \
-w=/go/src/github.com/vmware/load-balancer-and-ingress-services-for-kubernetes \
-v /home/aviuser/ako-repo-fork/load-balancer-and-ingress-services-for-kubernetes:/go/src/github.com/vmware/load-balancer-and-ingress-services-for-kubernetes golang:bullseye \
go test -v -mod=vendor github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/evhtests -failfast -timeout 0 -coverprofile cover-11.out -coverpkg=./...
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/evhtests	1328.265s	coverage: 38.7% of statements in ./...


sudo docker run \
-w=/go/src/github.com/vmware/load-balancer-and-ingress-services-for-kubernetes \
-v /home/aviuser/ako-repo-fork/load-balancer-and-ingress-services-for-kubernetes:/go/src/github.com/vmware/load-balancer-and-ingress-services-for-kubernetes golang:bullseye \
go test -v -mod=vendor github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/evhtests -failfast -timeout 0 -isVipPerNS=true -coverprofile cover-12.out -coverpkg=./...
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/evhtests	1233.669s	coverage: 38.1% of statements in ./...


sudo docker run \
-w=/go/src/github.com/vmware/load-balancer-and-ingress-services-for-kubernetes \
-v /home/aviuser/ako-repo-fork/load-balancer-and-ingress-services-for-kubernetes:/go/src/github.com/vmware/load-balancer-and-ingress-services-for-kubernetes golang:bullseye \
go test -v -mod=vendor github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/dedicatedevhtests -failfast -coverprofile cover-13.out -coverpkg=./...
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/dedicatedevhtests	338.401s	coverage: 27.8% of statements in ./...


sudo docker run \
-w=/go/src/github.com/vmware/load-balancer-and-ingress-services-for-kubernetes \
-v /home/aviuser/ako-repo-fork/load-balancer-and-ingress-services-for-kubernetes:/go/src/github.com/vmware/load-balancer-and-ingress-services-for-kubernetes golang:bullseye \
go test -v -mod=vendor github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/dedicatedevhtests -failfast -isVipPerNS=true -coverprofile cover-14.out -coverpkg=./...
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/dedicatedevhtests	434.403s	coverage: 28.2% of statements in ./...


ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/oshiftroutetests	1268.021s	coverage: 33.2% of statements in ./...


ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/bootuptests	20.151s	coverage: 4.3% of statements in ./...


ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/multicloudtests	170.444s	coverage: 8.4% of statements in ./...


ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/advl4tests	40.600s	coverage: 17.6% of statements in ./...


ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/namespacesynctests	152.349s	coverage: 21.7% of statements in ./...


ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/servicesapitests	79.004s	coverage: 22.9% of statements in ./...


ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/npltests	116.805s	coverage: 24.2% of statements in ./...


ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/dedicatedvstests	154.414s	coverage: 29.8% of statements in ./...


ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/hatests	33.851s	coverage: 25.7% of statements in ./...


sudo docker run \
-w=/go/src/github.com/vmware/load-balancer-and-ingress-services-for-kubernetes \
-v /home/aviuser/ako-repo-fork/load-balancer-and-ingress-services-for-kubernetes:/go/src/github.com/vmware/load-balancer-and-ingress-services-for-kubernetes golang:bullseye \
go test -v -mod=vendor github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/cnitests -failfast -cniPlugin=calico -coverprofile cover-18.out -coverpkg=./...
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/cnitests	103.552s	coverage: 13.5% of statements in ./...


sudo docker run \
-w=/go/src/github.com/vmware/load-balancer-and-ingress-services-for-kubernetes \
-v /home/aviuser/ako-repo-fork/load-balancer-and-ingress-services-for-kubernetes:/go/src/github.com/vmware/load-balancer-and-ingress-services-for-kubernetes golang:bullseye \
go test -v -mod=vendor github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/cnitests -failfast -cniPlugin=cilium -coverprofile cover-19.out -coverpkg=./...
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/cnitests	27.263s	coverage: 13.2% of statements in ./...


PASS  Test avi-secret creation when avi controller credentials are specified or not specified in values.yaml	tests/avi-secret_test.yaml
PASS  Test AKO's ClusterRole with GatewayAPI	tests/clusterrole_test.yaml
PASS  Test GatewayClass creation with GatewayAPI	tests/gatewayclass_test.yaml
PASS  Test AKO's StatefulSet with GatewayAPI	tests/statefulset_test.yaml

Charts:      1 passed, 1 total
Test Suites: 4 passed, 4 total
Tests:       9 passed, 9 total
Snapshot:    0 passed, 0 total
Time:        52.844564ms


	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests		coverage: 0.0% of statements
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/graphlayer	244.752s	coverage: 17.6% of statements in ./...
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/ingestion	270.482s	coverage: 3.0% of statements in ./...
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/status	310.677s	coverage: 12.2% of statements in ./...
```

**Comment by DixitAakash** [comment]
build ako

**Pull request merged**
