### PR TITLE
AKO operator changes for networkName to VipNetworkList migration

### PR DESCRIPTION
**Pull request by monotosh-avi**

### CODE REVIEW

**Comment by RiyaGaniga-avi** [comment]
@monotosh-avi Can you update https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/blob/master/ako-operator/helm/ako-operator/templates/akoconfig.yaml also?

**Comment by monotosh-avi** [comment]
> @monotosh-avi Can you update https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/blob/master/ako-operator/helm/ako-operator/templates/akoconfig.yaml and https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/blob/master/ako-operator/helm/ako-operator/values.yaml also?

@RiyaGaniga-avi Thanks. Updated those files.

**Comment by RiyaGaniga-avi** [comment]
build ako

**Comment by monotosh-avi** [comment]
build ako

**Review by RiyaGaniga-avi — APPROVED** [review]

**Review by sudswasavi — APPROVED** [review]

**Pull request merged**
