### PR TITLE
Provide NetworkName via AviVsVipNode graph layer consistently

### PR DESCRIPTION
**Pull request by chauhanshubham**

### CODE REVIEW

**Review by monotosh-avi — APPROVED** [review]

**Review by sudswasavi — COMMENTED** [review]
@monotosh-avi / @chauhanshubham  will this PR cause existing releases to make a PUT call on vsvip upon upgrade for all the vips?

**Comment by chauhanshubham** [comment]
> @monotosh-avi / @chauhanshubham will this PR cause existing releases to make a PUT call on vsvip upon upgrade for all the vips?

probably not because of the `networkName != ""` check?

**Comment by monotosh-avi** [comment]
> > @monotosh-avi / @chauhanshubham will this PR cause existing releases to make a PUT call on vsvip upon upgrade for all the vips?
> 
> probably not because of the `networkName != ""` check?

I think it is going to change the checksum. But I think in this release vsvip checksum is going to change due to multiple changes.

**Comment by sudswasavi** [comment]
Merging this now for feature completeness but changing `networkName` has to be re-looked at separately since we may need more changes to make it work. cc @aaha97

**Review by sudswasavi — APPROVED** [review]

**Pull request merged**
