### PR TITLE
Multi-port service support

### PR DESCRIPTION
**Pull request by sudswasavi**
Added a note for multi-port service support that supports port numbers from AKO 1.5.1 along with strings.

### CODE REVIEW

**Review by monotosh-avi — APPROVED** [review]

**Comment by sudswasavi** [comment]
build ako

**Comment by sudswasavi** [comment]
build ako

**Comment by monotosh-avi** [comment]
build ako

**Comment by sudswasavi** [comment]
build ako

**Review by akshayhavile — APPROVED** [review]

**Pull request merged**
