### PR TITLE
Documentation: Release notes for 1.6.4

### PR DESCRIPTION
**Pull request by akshayhavile**
Documentation

As we do not have release 1.6.3 on harbor, adding items from 1.6.3 to 1.6.4

### CODE REVIEW

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
skip build

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Review by chauhanshubham — APPROVED** [review]

**Review by swathinsankaran — APPROVED** [review]

**Comment by akshayhavile** [comment]
build ako

**Comment by swathinsankaran** [comment]
build ako

**Review by aaha97 — APPROVED** [review]

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
Merging without PR sanity check.

**Pull request merged**
