### PR TITLE
Update values.yaml

### PR DESCRIPTION
**Pull request by canad1an**
Fixed wording of ipv6

### CODE REVIEW

**Review by akshayhavile — APPROVED** [review]

**Review by swathinsankaran — APPROVED** [review]

**Comment by swathinsankaran** [comment]
@canad1an please sign the contributor license agreement.

**Comment by canad1an** [comment]
Signed.

**Comment by canad1an** [comment]
I'm now part of the VMware org.

**Comment by swathinsankaran** [comment]
build ako

**Comment by swathinsankaran** [comment]
Signed

**Comment by swathinsankaran** [comment]
These changes are included in PR #997. Hence closing this.

**Pull request closed without merging**
