### PR TITLE
AV-199362: Route Status Reason field update with vsuuid and controller uuid

### PR DESCRIPTION
**Pull request by akshayhavile**
As part of this PR, AKO will populate status and annotations of route with vs uuid and controller uuid to have backward compatibility with AMKO during upgrade.

### CODE REVIEW

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Review by pkoshtavmware — APPROVED** [review]
LGTM

**Review by arihantg — APPROVED** [review]
LGTM

**Pull request merged**
