### PR TITLE
AV-206824 Update port in vhmatch of child vs

### PR DESCRIPTION
**Pull request by arihantg**
```
 make gatewayapitests 
sudo docker run \
-e ENDPOINTSLICES_ENABLED="false" \
-w=/go/src/github.com/vmware/load-balancer-and-ingress-services-for-kubernetes \
-v /home/aviuser/myfork/load-balancer-and-ingress-services-for-kubernetes:/go/src/github.com/vmware/load-balancer-and-ingress-services-for-kubernetes golang:bullseye \
go test -mod=vendor github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/... -failfast -timeout 0 -coverprofile cover-20.out -coverpkg=./...
        github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests               coverage: 0.0% of statements
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/graphlayer    472.123s        coverage: 18.4% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/ingestion     220.594s        coverage: 2.8% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/npltests      60.369s coverage: 15.8% of statements in ./...
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/status        300.894s        coverage: 12.7% of statements in ./...

```

### CODE REVIEW

**Comment by arihantg** [comment]
build ako

**Comment by pkoshtavmware** [comment]
Can you please attach FT run result here ?

**Review by pkoshtavmware — APPROVED** [review]
LGTM

**Comment by arihantg** [comment]
FT Result
```
**********************************************************************************************************************************
*                                          AviTest Test Cases Execution Summary Report                                           *
**********************************************************************************************************************************
+----------------------------------------------------------------------------------+----------------+---------------------+-------------+-------------+
| Absolute Path:Test case                                                          |     Results    |       Duration      |  Start Time |   End Time  |
+----------------------------------------------------------------------------------+----------------+---------------------+-------------+-------------+
|      Test Suite Path and Name : test/avitest/functional/ako/ako-gw-              |                |                     |             |             |
| api/test_gateway.py                                                              |                |                     |             |             |
| ++++++++++++++++++++++++++++++++++++++++                                         |                |                     |             |             |
| TestGateway.test_setup_configuration                                             |     PASSED     |       00:00:44      |   11:41:45  |   11:42:29  |
| TestGateway.test_gateway_crud                                                    |     PASSED     |       00:03:12      |   11:42:29  |   11:45:41  |
| TestGateway.test_update_gateway_without_gateway_class                            |     PASSED     |       00:02:12      |   11:45:41  |   11:47:54  |
| TestGateway.test_gateway_with_different_hosts                                    |     PASSED     |       00:01:26      |   11:47:54  |   11:49:21  |
| TestGateway.test_parent_vs_from_secure_gateway                                   |     PASSED     |       00:01:26      |   11:49:21  |   11:50:47  |
| TestGateway.test_parent_vs_from_insecure_gateway                                 |     PASSED     |       00:01:56      |   11:50:47  |   11:52:44  |
| TestGateway.test_gateway_with_static_ip_address                                  |     PASSED     |       00:02:42      |   11:52:44  |   11:55:26  |
| TestGateway.test_gateway_with_invalid_secret_ref                                 |     FAILED     |       00:09:12      |   11:55:26  |   12:04:39  |
| TestGateway.test_delete_configurations                                           |     PASSED     |       00:00:50      |   12:04:40  |   12:05:30  |
| -------------------------------------------------------------------------------- |  ------------  |     -----------     | ----------- | ----------- |
|                                                                                  |    Passed: 8   |                     |             |             |
|                                                                                  |    Failed:1    |                     |             |             |
|  Total test cases: 9                                                             |    Skipped:0   | Total Time:00:23:44 |             |             |
+----------------------------------------------------------------------------------+----------------+---------------------+-------------+-------------+
[2024-10-15 12:05:57] :INFO: [logger_utils timed:58] calc_exc_time: 'display_summary' - 0.01 sec
[2024-10-15 12:05:57] :INFO: [conftest post_process_avitest_markers:486] Post Processing Avitest Markers, when:teardown, outcome:passed
Rebot framework is generating html file...
Time taken for rebot to generate html file 0.00 seconds

Logs combined. Removing individual logs....

**********************************************************************************************************************************
*                                          AviTest Test Cases Execution Summary Report                                           *
**********************************************************************************************************************************
+----------------------------------------------------------------------------------+----------------+---------------------+-------------+-------------+
| Absolute Path:Test case                                                          |     Results    |       Duration      |  Start Time |   End Time  |
+----------------------------------------------------------------------------------+----------------+---------------------+-------------+-------------+
|      Test Suite Path and Name : test/avitest/functional/ako/ako-gw-              |                |                     |             |             |
| api/test_http_route.py                                                           |                |                     |             |             |
| ++++++++++++++++++++++++++++++++++++++++                                         |                |                     |             |             |
| TestHttpRoute.test_setup_configuration                                           |     PASSED     |       00:01:14      |   12:08:57  |   12:10:11  |
| TestHttpRoute.test_insecure_httproute                                            |     PASSED     |       00:01:43      |   12:10:11  |   12:11:54  |
| TestHttpRoute.test_secure_httproute                                              |     PASSED     |       00:01:43      |   12:11:54  |   12:13:37  |
| TestHttpRoute.test_httproute_match_crud                                          |     PASSED     |       00:02:29      |   12:13:37  |   12:16:07  |
| TestHttpRoute.test_httproute_match_append_header_crud                            |     PASSED     |       00:02:29      |   12:16:07  |   12:18:37  |
| TestHttpRoute.test_httproute_match_replace_header_crud                           |     PASSED     |       00:02:29      |   12:18:37  |   12:21:07  |
| TestHttpRoute.test_httproute_filter_crud                                         |    SKIPPED     |       00:00:41      |   12:21:07  |   12:21:48  |
| TestHttpRoute.test_httproute_backendref_crud                                     |     PASSED     |       00:02:13      |   12:21:48  |   12:24:02  |
| TestHttpRoute.test_httproute_multiple_rules                                      |     PASSED     |       00:02:14      |   12:24:02  |   12:26:16  |
| TestHttpRoute.test_http_route_with_multiple_gateways                             |     PASSED     |       00:02:44      |   12:26:16  |   12:29:01  |
| TestHttpRoute.test_multiple_http_routes_with_gateway                             |     PASSED     |       00:03:15      |   12:29:01  |   12:32:16  |
| TestHttpRoute.test_http_route_same_path_different_headers                        |     PASSED     |       00:02:14      |   12:32:16  |   12:34:31  |
| TestHttpRoute.test_httproute_multiple_hosts                                      |     PASSED     |       00:02:44      |   12:34:31  |   12:37:16  |
| TestHttpRoute.test_traffic_split                                                 |     PASSED     |       00:04:23      |   12:37:16  |   12:41:39  |
| TestHttpRoute.test_delete_configurations                                         |     PASSED     |       00:02:01      |   12:41:39  |   12:43:40  |
| -------------------------------------------------------------------------------- |  ------------  |     -----------     | ----------- | ----------- |
|                                                                                  |   Passed: 14   |                     |             |             |
|                                                                                  |    Failed:0    |                     |             |             |
|  Total test cases: 15                                                            |    Skipped:1   | Total Time:00:34:43 |             |             |
+----------------------------------------------------------------------------------+----------------+---------------------+-------------+-------------+
[2024-10-15 12:44:07] :INFO: [logger_utils timed:58] calc_exc_time: 'display_summary' - 0.01 sec
[2024-10-15 12:44:07] :INFO: [conftest post_process_avitest_markers:486] Post Processing Avitest Markers, when:teardown, outcome:passed
Rebot framework is generating html file...
Time taken for rebot to generate html file 0.00 seconds

Logs combined. Removing individual logs....

```

**Review by ashishnayak96 — APPROVED** [review]

**Comment by apalsule** [comment]
merging as build ako pipeline is failing.

**Pull request merged**
