### PR TITLE
migrate AKO docs and changelog from avi-helm-charts repository

### PR DESCRIPTION
**Pull request by chauhanshubham**
We'll be discontinuing the avi-helm-charts repo, so the AKO/AMKO docs are being moved to their respective repos.

Signed-off-by: Shubham Chauhan <shchauhan@vmware.com>
Signed-off-by: Sudipto Biswas <bsudipto@vmware.com>
Signed-off-by: Monotosh Das <dmonotosh@vmware.com>
Signed-off-by: Parikshit Manur <parikshitm@vmware.com>
Signed-off-by: Akshay Havile <ahavile@vmware.com>
Signed-off-by: Hemant Shaw <hshaw@vmware.com>
Signed-off-by: Anish Hebbar <hanish@vmware.com>
Signed-off-by: Riya Ganiga <riyag@vmware.com>
Signed-off-by: Arif Awate <aawate@vmware.com>
Signed-off-by: Nikunj Rathi <nikunjr@vmware.com>
Signed-off-by: Thorsten Schifferdecker <curx@users.noreply.github.com>

### CODE REVIEW

**Review by sudswasavi — COMMENTED** [review]
Unfortunately looks like we couldn't preserve the git history.
In such a case, can you pls mark this commit as "Signed-Of-By" - all the contributors who posted on the older repo and get them to approve this PR? 
(https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for)

Thanks for getting this done.

**Review by rathinikunj — DISMISSED** [review]

**Comment by sudswasavi** [comment]
Also can you pls add a succinct commit message that describes why we are doing this change and ack the contributors via the signed off field.

**Comment by chauhanshubham** [comment]
build ako

**Review by RiyaGaniga-avi — APPROVED** [review]

**Review by monotosh-avi — APPROVED** [review]

**Review by parimanur — APPROVED** [review]

**Review by sudswasavi — APPROVED** [review]

**Review by hemantavi — APPROVED** [review]

**Review by akshayhavile — APPROVED** [review]

**Review by rathinikunj — APPROVED** [review]
Looks good

**Review by anish-avi — APPROVED** [review]

**Review by aaha97 — APPROVED** [review]

**Pull request merged**
