### PR TITLE
Create a single sslkey per Tenant for default secret

### PR DESCRIPTION
**Pull request by abhishekbsingh**

### CODE REVIEW

**Comment by Dhivyaaj** [comment]
No JIRA Ids found for the PR. Jira id is mandatory to update fix version in jira.                                            Please update respective Jira id in PR title or commit message                                            if the PR is intented for default branches of repo.                                            For mandatory exemptions, comment trigger phrase 'skip jira-id-check' in PR.                                            For manual trigger, comment trigger phrase 'run jira-id-check' in PR.

**Comment by abhishekbsingh** [comment]
build ako

**Comment by abhishekbsingh** [comment]
build ako

**Comment by abhishekbsingh** [comment]
build ako

**Review by akshayhavile — COMMENTED** [review]
@abhishekbsingh: Few queries:
1. This cert is attached to each VS. How are we ensuring that we will avoid multiple POST calls for same certificate. Reason: This will result in `object already exist` error and then it will go into retry loop.
2. Did we test upgrade scenario?

**Comment by abhishekbsingh** [comment]
> @abhishekbsingh: Few queries:
> 
> 1. This cert is attached to each VS. How are we ensuring that we will avoid multiple POST calls for same certificate. Reason: This will result in `object already exist` error and then it will go into retry loop.
> 2. Did we test upgrade scenario?

I tested the upgrade scenario by running an AKO binary on a k8s setup which already had VS and dedicated certs - there it works fine as the vs cache obj is not nil and ssl cache obj will be checked in that case.
However, for new VS it may lead to Post calls as the ssl cache object is passed as nil. I will update the PR to get the ssl cache for all VS. Thanks.

**Review by akshayhavile — APPROVED** [review]

**Comment by akshayhavile** [comment]
build ako

**Review by arihantg — APPROVED** [review]

**Comment by abhishekbsingh** [comment]
build ako

**Comment by abhishekbsingh** [comment]
build ako

**Comment by akshayhavile** [comment]
skip jira-id-check

**Comment by akshayhavile** [comment]
skip jira-id check

**Comment by Dhivyaaj** [comment]
No JIRA Ids found for the PR. Jira id is mandatory to update fix version in jira.                                            Please update respective Jira id in PR title or commit message                                            if the PR is intented for default branches of repo.                                            For mandatory exemptions, comment trigger phrase 'skip jira-id-check' in PR.                                            For manual trigger, comment trigger phrase 'run jira-id-check' in PR.

**Comment by abhishekbsingh** [comment]
build ako

**Comment by abhishekbsingh** [comment]
build ako

**Comment by abhishekbsingh** [comment]
build ako

**Comment by abhishekbsingh** [comment]
build ako

**Comment by abhishekbsingh** [comment]
build ako

**Comment by abhishekbsingh** [comment]
build ako

**Comment by akshayhavile** [comment]
skip jira-id check

**Comment by akshayhavile** [comment]
skip jira-id check

**Comment by Dhivyaaj** [comment]
No JIRA Ids found for the PR. Jira id is mandatory to update fix version in jira.                                            Please update respective Jira id in PR title or commit message                                            if the PR is intented for default branches of repo.                                            For mandatory exemptions, comment trigger phrase 'skip jira-id-check' in PR.                                            For manual trigger, comment trigger phrase 'run jira-id-check' in PR.

**Comment by abhishekbsingh** [comment]
skip jira-id-check

**Comment by abhishekbsingh** [comment]
build ako

**Comment by abhishekbsingh** [comment]
build ako

**Comment by akshayhavile** [comment]
build ako

**Comment by abhishekbsingh** [comment]
```
coverage: 29.8% of statements in ./...
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/dedicatedvstests	154.896s	coverage: 29.8% of statements in ./...
abishekb@K3WVXX0J27:~/load-balancer-and-ingress-services-for-kubernetes$
abishekb@K3WVXX0J27:~/load-balancer-and-ingress-services-for-kubernetes$
abishekb@K3WVXX0J27:~/load-balancer-and-ingress-services-for-kubernetes$ git branch
  master
  release-1.12.1
  release-1.12.1-tkg
  release-1.12.2
  release-1.9.3-tkg
  topic/abishekb/default-cert-changes
* topic/abishekb/default-cert-changes-1.12.2


coverage: 25.6% of statements in ./...
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/hatests	34.024s	coverage: 25.6% of statements in ./...
abishekb@K3WVXX0J27:~/load-balancer-and-ingress-services-for-kubernetes$ git branch
  master
  release-1.12.1
  release-1.12.1-tkg
  release-1.12.2
  release-1.9.3-tkg
  topic/abishekb/default-cert-changes
* topic/abishekb/default-cert-changes-1.12.2


abishekb@K3WVXX0J27:~/load-balancer-and-ingress-services-for-kubernetes$ git branch
  master
  release-1.12.1
  release-1.12.1-tkg
  release-1.12.2
  release-1.9.3-tkg
  topic/abishekb/default-cert-changes
* topic/abishekb/default-cert-changes-1.12.2
abishekb@K3WVXX0J27:~/load-balancer-and-ingress-services-for-kubernetes$ make calicotests | grep ok
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/cnitests	103.709s	coverage: 13.4% of statements in ./...
abishekb@K3WVXX0J27:~/load-balancer-and-ingress-services-for-kubernetes$ make ciliumtests | grep ok
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/cnitests	27.328s	coverage: 13.1% of statements in ./...


abishekb@K3WVXX0J27:~/load-balancer-and-ingress-services-for-kubernetes$ make gatewayapitests
sudo docker run \
	-w=/go/src/github.com/vmware/load-balancer-and-ingress-services-for-kubernetes \
	-v /Users/abishekb/load-balancer-and-ingress-services-for-kubernetes:/go/src/github.com/vmware/load-balancer-and-ingress-services-for-kubernetes golang:bullseye \
	go test -mod=vendor github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/... -failfast -timeout 0 -coverprofile cover-20.out -coverpkg=./...
	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests		coverage: 0.0% of statements
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/graphlayer	245.105s	coverage: 17.6% of statements in ./...
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/ingestion	270.677s	coverage: 3.0% of statements in ./...
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/status	310.888s	coverage: 11.9% of statements in ./...
```

**Comment by abhishekbsingh** [comment]
build ako

**Pull request merged**
