### PR TITLE
doc update for passthrough Ingress

### PR DESCRIPTION
**Pull request by monotosh-avi**

### CODE REVIEW

**Comment by chauhanshubham** [comment]
skip build

**Comment by chauhanshubham** [comment]
build ako

**Comment by chauhanshubham** [comment]
skip build

**Comment by chauhanshubham** [comment]
skip build

**Comment by chauhanshubham** [comment]
skip-ci

**Review by sudswasavi — APPROVED** [review]

**Review by chauhanshubham — APPROVED** [review]

**Pull request merged**
